# Generated by Django 3.2.23 on 2024-07-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$BbLBKCcCtxRPEYeonvAZe2$qOOC8kfYH0WzdL7bXzg0w2/gAkBwMxhY+cOx654HLms=', max_length=128, verbose_name='password'),
        ),
    ]
