# Generated by Django 3.2.23 on 2024-07-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$EhK8oHTH4D8JkIZPPi1BBX$cKaSMYbSJgKBTXYLhrF/2T6F7hJ1qGQYAwG6NmEjWRc=', max_length=128, verbose_name='password'),
        ),
    ]
