# Generated by Django 3.2.23 on 2024-08-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_auto_20240805_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$z9z0pg5j36uh8vKy6RtVn1$EcD6ickIxcjod+30oU4vh5ferqQ+Rrj3xXViwwEkeCg=', max_length=128, verbose_name='password'),
        ),
    ]
